netgen_information_collection:
    system:
        default:
            captcha:
                enabled: false
                secret: 'CHANGE_ME'
                site_key: 'CHANGE_ME'
            action_config:
                email:
                    attachments:
                        enabled: true
                    templates:
                        default: "@ibexadesign/info_collection/email.html.twig"
                    default_variables:
                        sender: "%collected_info_sender%"
                        recipient: "%collected_info_recipient%"
            actions:
                default:
                    - database
                    - email
                    - Netgen\Bundle\SiteBundle\InfoCollection\Action\NewsletterAction
