block_types:
    ezcomponent_hero:
        name: 'Hero'
        definition_identifier: ezcomponent
        icon: '/bundles/app/images/icon-component-hero.svg'
        defaults:
            view_type: hero_style_1
            parameters:
                content_type_identifier: ng_component_hero

    ezcomponent_about:
        name: 'About'
        definition_identifier: ezcomponent
        icon: '/bundles/app/images/icon-component-about.svg'
        defaults:
            view_type: about_style_1
            parameters:
                content_type_identifier: ng_component_about

    ezcomponent_features:
        name: 'Features'
        definition_identifier: ezcomponent
        icon: '/bundles/app/images/icon-component-features.svg'
        defaults:
            view_type: features_style_1
            parameters:
                content_type_identifier: ng_component_features

    ezcomponent_logos:
        name: 'Logos'
        definition_identifier: ezcomponent
        icon: '/bundles/app/images/icon-component-logos.svg'
        defaults:
            view_type: logo_style_1
            parameters:
                content_type_identifier: ng_component_logos

block_type_groups:
    components:
        block_types: 
            - ezcomponent_hero
            - ezcomponent_about
            - ezcomponent_features
            - ezcomponent_logos
